Repository colibriproject-dev/colibri-sdk-go, pull requests merged in 2023-10, with the labels that each got.

#49 feat: change storage upload return
  pkg/storage/gcp.go
Labels: size/S

#51 feat: change gcp storage url
  pkg/storage/gcp.go
Labels: size/XS

#54 chore: update modules
  go.mod
  go.sum
Labels: size/M

#55 chore: enable GCP
  pkg/base/cloud/cloud.go
Labels: size/XS

#57 fix: github.com/gofiber/swagger version
  go.mod
  go.sum
Labels: size/XS

#58 fix: gcp pubsub project id config
  pkg/messaging/gcp.go
Labels: size/XS

#64 check if rest server is closed successfully.
  pkg/web/restserver/server.go
Labels: size/XS
