Repository colibriproject-dev/colibri-sdk-go, pull requests merged in 2023-11, with the labels that each got.

#67 fix: add condition when i try to add photo-url in create firebase user
  pkg/base/security/firebase.go
Labels: bug, size/XS

#68 add support to array field in postgres mapping
  development-environment/database/add-dogs.sql
  development-environment/database/clear-database.sql
  development-environment/database/migrations/000001_schema.up.sql
  development-environment/database/schema.sql
  pkg/database/sqlDB/query_test.go
  pkg/database/sqlDB/sql_db.go
  pkg/database/sqlDB/sql_db_test.go
Labels: size/S

#69 add JsonB type
  pkg/base/types/json.go
  pkg/base/types/json_test.go
Labels: enhancement, size/S
