Repository colibriproject-dev/colibri-sdk-go, pull requests merged in 2024-04, with the labels that each got.

#73 Update authentication context and add custom auth middleware
  pkg/base/security/authentication_context.go
  pkg/base/security/authentication_context_test.go
  pkg/database/sqlDB/sql_db.go
  pkg/messaging/provider_message.go
  pkg/web/restserver/fiber_server.go
  pkg/web/restserver/middlewares.go
  pkg/web/restserver/server.go
  pkg/web/restserver/server_test.go
Labels: size/S, size/M

#81 Update Go version and go.opentelemetry.io/contrib version
  .github/workflows/quality.yaml
  go.mod
  go.sum
Labels: size/XS, size/S

#83 chore: evol observer module
  pkg/base/config/config.go
  pkg/base/config/config_test.go
  pkg/base/observer/single_wait_group.go
  pkg/base/observer/single_wait_group_test.go
  pkg/base/observer/subject.go
  pkg/database/cacheDB/cache_db.go
  pkg/database/sqlDB/sql_db.go
  pkg/messaging/messaging.go
  pkg/web/restserver/observer.go
  pkg/web/restserver/observer_test.go
  pkg/web/restserver/server.go
  pkg/web/restserver/server_test.go
Labels: bug, size/M
