Repository colibriproject-dev/colibri-sdk-go, pull requests merged in 2025-04, with the labels that each got.

#115 chore: increase coverage
  .github/workflows/quality.yaml
  pkg/base/cloud/cloud.go
  pkg/base/cloud/cloud_test.go
  pkg/base/config/config.go
  pkg/base/config/config_test.go
  pkg/base/test/base.go
  pkg/base/test/base_test.go
  pkg/database/sqlDB/sql_db_test.go
Labels: size/S, size/M

#119 Add GCP messaging test and improve error handling
  pkg/messaging/messaging_test.go
Labels: size/S

#120 chore: config sonar exclusion
  .github/workflows/quality.yaml
Labels: size/XS
