Repository colibriproject-dev/colibri-sdk-go, pull requests merged in 2025-05, with the labels that each got.

#121 fix: correct comments and pointer receiver in observer
  pkg/base/observer/subject.go
Labels: size/XS

#122 chore: improve restserver documentation
  pkg/web/restserver/route.go
  pkg/web/restserver/server.go
Labels: size/S

#124 chore: update new relic version
  go.mod
  go.sum
Labels: size/S

#125 Refactor/constants variables documentation
  pkg/base/config/config.go
  pkg/base/config/config_test.go
  pkg/base/monitoring/colibri-monitoring-base/monitoring.go
  pkg/base/types/iso_date.go
  pkg/base/types/iso_time.go
  pkg/base/types/json.go
  pkg/base/types/json_test.go
  pkg/base/types/null_bool.go
  pkg/base/types/null_date_time.go
  pkg/base/types/null_float_64.go
  pkg/base/types/null_int_16.go
  pkg/base/types/null_int_32.go
  pkg/base/types/null_int_64.go
  pkg/base/types/null_string.go
  pkg/base/types/page.go
  pkg/base/types/sort.go
  pkg/base/validator/validator.go
  pkg/database/cacheDB/cache.go
  pkg/database/sqlDB/migrations.go
  pkg/database/sqlDB/observer.go
  pkg/database/sqlDB/page_query.go
  pkg/database/sqlDB/page_query_test.go
  pkg/database/sqlDB/query.go
  pkg/database/sqlDB/query_test.go
  pkg/database/sqlDB/reflection.go
  pkg/database/sqlDB/sql_db.go
  pkg/database/sqlDB/sql_transaction.go
  pkg/database/sqlDB/sql_transaction_test.go
  pkg/database/sqlDB/statement.go
  pkg/database/sqlDB/statement_test.go
  pkg/di/container.go
  pkg/di/dependency_bean.go
  pkg/messaging/messaging.go
  pkg/messaging/provider_message.go
  pkg/storage/gcp.go
  pkg/storage/storage.go
  pkg/web/restclient/client.go
  pkg/web/restserver/server.go
  pkg/web/restserver/test_response.go
  pkg/web/restserver/web_context.go
Labels: size/M

#127 fix and prepare next release version
  pkg/base/config/config.go
Labels: size/XS
